// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Driver.h"
#include "../Robotmap.h"
Driver::Driver() : Subsystem("Driver") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	leftRearController = RobotMap::driverLeftRearController;
	leftFrontController = RobotMap::driverLeftFrontController;
	rightFrontController = RobotMap::driverRightFrontController;
	rightRearController = RobotMap::driverRightRearController;
	robotDrive41 = RobotMap::driverRobotDrive41;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void Driver::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new DrivewithJoystick());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
		
void Driver::takeJoystickInpute(Joystick* controller)
{
		robotDrive41->MecanumDrive_Cartesian(controller->GetX(), controller->GetY(), controller->GetZ(), 0);
}
void Driver::stop()
{
		robotDrive41->drive(0.0, 0.0);
}
